In [17]:
pip install numpy

In [18]:
import numpy as np
print(np.__version__)

2.1.3


In [19]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [20]:
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [21]:
import numpy as np
arr = np.zeros((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
import numpy as np
arr = np.zeros((10,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
import numpy as np
arr = np.ones((5,7))
print(arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [25]:
import numpy as np
arr=np.full((4,7),9)
print(arr)

[[9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]
 [9 9 9 9 9 9 9]]


In [26]:
import numpy as np
arr = np.empty((5,5))
print(arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [27]:
import numpy as np
arr = np.eye(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
import numpy as np
arr = np.arange(1,100)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [32]:
import numpy as np
arr = np.arange(2,100,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96
 98]


In [36]:
import numpy as np
arr = np.arange(1,100,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [38]:
import numpy as np
arr = np.linspace(1,20,7)
print(arr)

[ 1.          4.16666667  7.33333333 10.5        13.66666667 16.83333333
 20.        ]


In [39]:
import numpy as np
arr = np.random.rand(10)
print(arr)

[0.94114372 0.9022689  0.05793484 0.64498993 0.7427483  0.68872477
 0.16037175 0.33859988 0.69403801 0.02442364]


In [40]:
import numpy as np
arr = np.random.randn(10)
print(arr)

[-0.10558132 -2.3463714  -0.31977503 -0.17229423  0.85527177 -0.46641108
  0.24446427 -0.04919743 -1.76663344 -0.77000207]


In [51]:
import numpy as np
arr = np.random.randint(10)
print(arr)

1


In [59]:
import numpy as np
colours=["Red","Green","pink","Orange","Blue","White","Black","Yellow"]
print(np.random.choice(colours,2))

['Black' 'White']


In [60]:
import numpy as np
arr = np.array([1,2,3])
new=arr.copy()
new[1]=100
print("Array value is:",arr)
print("Copy value is:",new)

Array value is: [1 2 3]
Copy value is: [  1 100   3]


In [61]:
import numpy as np
arr = np.array([1,2,3])
new=arr.view()
new[1]=100
print("Array value is:",arr)
print("View value is:",new)

Array value is: [  1 100   3]
View value is: [  1 100   3]


In [62]:
import numpy as np
arr = np.array([5,10,15,20,25,30])
arr+=10
print("Updated array value is:",arr)

Updated array value is: [15 20 25 30 35 40]


In [64]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(np.add(a,b))

[ 7  9 11 13 15]


In [73]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([5,4,3,2,1])
print(np.multiply(a,b))

[5 8 9 8 5]


In [72]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([15,20,25,30,35])
print(np.subtract(a,b))

[-14 -18 -22 -26 -30]


In [71]:
import numpy as np
a=np.array([10,20,30,40,50])
b=np.array([1,2,3,4,5])
print(np.divide(a,b))

[10. 10. 10. 10. 10.]


In [75]:
import numpy as np
a=np.array([1,2,3,4,5])
b=np.array([1,2,3,4,5])
print(np.dot(a,b))

55


In [76]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(sum(arr))

45


In [78]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(min(arr))

1


In [79]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(max(arr))

9


In [83]:
import numpy as np
arr=np.array([1,4,9,25,125])

print(np.sqrt(arr))

[ 1.          2.          3.          5.         11.18033989]


In [85]:
import numpy as np
arr=np.array([4,8,2,9,10,3])

print(np.sort(arr))

[ 2  3  4  8  9 10]


In [87]:
import numpy as np
arr=np.array([5,28,60,25,6])

print(np.unique(arr))

[ 5  6 25 28 60]


In [88]:
import numpy as np
arr=np.array([15,73,68,39,50])

print(arr.shape)

(5,)


In [92]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr.size)
print(arr.itemsize)
print(arr.ndim)
print(arr.dtype)

9
8
1
int64


In [98]:
import numpy as np
arr=np.array([[1,2,3,4],[5,4,3,2]])

print(arr.shape)
print(arr.ndim)
print(arr[0,1])
print(arr[1,1])
print(arr[:,1])

(2, 4)
2
2
4
[2 4]


In [99]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15])
print("Original array:",arr)
new=arr.reshape(5,3)
print(new)

Original array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
